README.md & Contribution.Md
LucasPilla/Sorting-Algorithms-Visualizer pull request #151
Opened 2022-10-13 19:47 UTC by highb33kay

This Project is amazing. Great Work. 

I  Made Improvement to the README.md page by adding Repo URL to clone. Improved Markdown syntax. Improved Contribution.md by adding more detail. 

Please Merge as HacktoberFest. Thank you.

2022-10-13 22:18 UTC, LucasPilla requested changes
Thank you for contributing. 
Just a quick question, what is the `.markdownlint.json` file for?

2022-10-14 03:06 UTC, highb33kay commented
hi @LucasPilla, Okay so according to Markdown Rules, Inlines HTML is not allowed by default, see [Rules](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md033). In order to use Inline HTML Without errors, you need to declare it in a .markdownlint.json file and that is what I did.

2022-10-14 03:13 UTC, highb33kay commented
I apologize for not explaining this in my first Commit Message.

2022-10-14 10:45 UTC, LucasPilla approved these changes

2022-10-14 10:45 UTC, merged